name: VÃ©rification du linting
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install back modules
        run: cd back && npm i --only-dev

      - name: ESLint back
        run: cd back && npm run lint
      - name: Install front modules
        run: cd front && npm i --only-dev
      - name: ESLint front
        run: cd front && npm run lint
      - name: Type check back
        run: cd back && npx tsc --noEmit
